# Generated by Django 4.0 on 2024-04-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='photo',
            field=models.ImageField(blank=True, upload_to='phone/'),
        ),
    ]
